#!/bin/sh

# Install the java dbus service
rm -f /usr/lib/luna/java/de.hlavka.minstatservice.jar
cp $IPKG_OFFLINE_ROOT/usr/lib/luna/java/de.hlavka.minstatservice.jar /usr/lib/luna/java/de.hlavka.minstatservice.jar
rm -f /usr/share/dbus-1/system-services/de.hlavka.minstatservice.service
cp $IPKG_OFFLINE_ROOT/usr/share/dbus-1/system-services/de.hlavka.minstatservice.service /usr/share/dbus-1/system-services/de.hlavka.minstatservice.service

# Install the upstart script
rm -f /etc/event.d/de.hlavka.minstatservice
cp $IPKG_OFFLINE_ROOT/etc/event.d/de.hlavka.minstatservice /etc/event.d/de.hlavka.minstatservice

stop java-serviceboot
start java-serviceboot

luna-send -n 1 palm://de.hlavka.minstatservice/getVersion {}

exit 0
