#!/bin/sh

# Stop the service
/sbin/stop de.hlavka.minstatservice

# Remove the java dbus service
rm -f /usr/lib/luna/java/de.hlavka.minstatservice.jar
rm -f /usr/share/dbus-1/system-services/de.hlavka.minstatservice.jar

# Remove the upstart script
rm -f /etc/event.d/de.hlavka.minstatservice

# Restart the service handler
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop java-serviceboot
    /sbin/start java-serviceboot
fi

exit 0
